runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /events/.*
  script: main.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: latest

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: 'google_compute_engine.json'
  GAE_USE_SOCKETS_HTTPLIB : '53778008'

basic_scaling:
  max_instances: 1
  idle_timeout: 10s
